### ISSUE TITLE
스터디 리스트 To-Do list

### ISSUE THREAD

**Issue by cok2exe** [ludative/studybooster-Client#7]
- [x] 페이지네이션 기능 추가
- [x] 검색 기능 추가
- [x] 북마크 기능 추가
- [ ] 비로그인 사용자 리스트 dim 처리 및 ex 문구 `스터디 부스터에 탑승하고 원하는 스터디에 가입하세요!`

- [x] alert 모달 추가 (window.confirm, alert ...)

**Comment by cok2exe** [comment]
**[컨벤션 자동화 툴 추가]**
husky, lint-staged 최신 버전 설치 시 node 버전 10 이상 필요해서
우선은 husky, lint-staged의 버전을 낮춤

**Comment by cok2exe** [comment]
**[토스트 메시지 추가]** (with kkangil)
withToast hoc와 함께 setToast로 사용
https://github.com/ludative/studybooster-Client/commit/a769fc119c30e15e698a5aa523f4a36955525424
